package com.vehicle.information.trending.rtoexam.rto.Task_utils;

public class Urls {
    public static String amazon_affiliate_id = "dtashion-rto-apps-21";
    public static String apps_url = "https://www.dtashion.com/api/v1.0/shopping/in/";
    public static String base_url = "https://www.tradetu.com/bus_api/public/api/v1/vaahan/";
    public static String base_url_v2 = "https://www.tradetu.com/rto/api/v2/vaahan/";
    public static boolean catch_external_site_link = true;
    public static String contact_us_email = "contact@vehiclertoapp.com";
    public static String cue_links_base_url = "https://linksredirect.com/?cid=28540&subid=sharedLink&source=linkkit&url=";
    public static String data_access_key = "T7v$rWKpu4qBMzuF p9S$dHKjHVmasgFj DrT$GhMnp{$FDx$k";
    public static String data_access_key_v2 = "mParivahan#2019@";
    public static String data_access_params_v2 = "doc_number=REG_NO doc_type=1 d_imei_number=dsflskdjflks d_token=dsfsdfs d_os_version=9 d_os_type=ANDROID d_model=MOTOROLA device_id=435jhfkjshfksfjsh virtual_rc=1";
    public static String data_access_point = "INTERNAL";
    public static String data_access_point_v2 = "WEB";
    public static String data_access_timestamp_format = "yyyyMMddHHmmss";
    public static String data_access_url = "https://mparivahan.parivahan.gov.in/api/user/rc-detail";
    public static String data_access_url_v2 = "https://mparivahan.parivahan.gov.in/api/vt-enc-rc";
    public static String flipkart_affiliate_id = "contacttr5";
    public static String inner_promotion_content = "{\"promotions\":[{\"promoName\":\"ShoppingBuddy - All In One Online Shopping App\",\"promoImage\":\"https://lh3.googleusercontent.com/D7A2b4kbNedpmddL3HAnzr5nKCULemc6o1q2dpH5nzr0ed9YcGSxXOu_ukA1u88L65s\",\"promoUrl\":\"https://onlineshoppingbrowser.page.link/iGuj\"},{\"promoName\":\"DealsDime.com - Cash On Deals\",\"promoImage\":\"https://res.cloudinary.com/dd6b3r1tf/image/upload/v1598276810/a8tlvdrql2ozbg1mzge4.png\",\"promoUrl\":\"https://www.dealsdime.com/?ref=rto-inner\"},{\"promoName\":\"Video Downloader for Facebook\",\"promoImage\":\"https://res.cloudinary.com/du8o9hpsu/image/upload/v1588589458/FB_Video_Downloader_appcgy.png\",\"promoUrl\":\"https://fbdownloader.page.link/y6N7\"},{\"promoName\":\"RTO Vehicle Information - Vehicle Owner Details\",\"promoImage\":\"https://res.cloudinary.com/dsaiqe6is/image/upload/v1555939074/RTO_vehicle_Information_n9if5u.png\",\"promoUrl\":\"https://play.google.com/store/apps/details?id=com.tradetu.trendingapps.vehicleinfo\"}]}";
    public static boolean is_promotion_available = true;
    public static String license_local_source_field_1 = "form_rcdl:tf_dlNO";
    public static String license_local_source_field_2 = "form_rcdl:tf_dob_input";
    public static String license_local_source_final_url = VehicleUtils.SUB_URL;
    public static String license_local_source_init_url = "https://parivahan.gov.in/rcdlstatus/?pur_cd=101";
    public static String license_screen = "NEW";
    public static String local_source_field_1 = "form_rcdl:tf_reg_no1";
    public static String local_source_field_2 = "form_rcdl:tf_reg_no2";
    public static String local_source_final_url = VehicleUtils.SUB_URL;
    public static String local_source_host_url = "parivahan.gov.in";
    public static String local_source_init_url = VehicleUtils.BASE_URL;
    public static boolean log_license_server_data = true;
    public static boolean log_server_data = true;
    public static String play_game_url = "https://220.win.qureka.com/";
    public static String promotion_content = "{\"promotions\":[{\"promoName\":\"Play & Win Cash\",\"promoImage\":\"https://www.tradetu.com/images/cricket_quiz.png\",\"promoUrl\":\"https://220.win.qureka.com/\"},{\"promoName\":\"DealsDime.com - Cash On Deals\",\"promoImage\":\"https://res.cloudinary.com/dd6b3r1tf/image/upload/v1598276810/a8tlvdrql2ozbg1mzge4.png\",\"promoUrl\":\"https://www.dealsdime.com/?ref=rto-home\"},{\"promoName\":\"ShoppingBuddy - All In One Online Shopping App\",\"promoImage\":\"https://lh3.googleusercontent.com/D7A2b4kbNedpmddL3HAnzr5nKCULemc6o1q2dpH5nzr0ed9YcGSxXOu_ukA1u88L65s\",\"promoUrl\":\"https://onlineshoppingbrowser.page.link/iGuj\"},{\"promoName\":\"RTO Vehicle Information - Vehicle Owner Details\",\"promoImage\":\"https://res.cloudinary.com/dsaiqe6is/image/upload/v1555939074/RTO_vehicle_Information_n9if5u.png\",\"promoUrl\":\"https://play.google.com/store/apps/details?id=com.tradetu.trendingapps.vehicleinfo\"},{\"promoName\":\"All Bank_Balance Enquiry - Bank_Balance Check\",\"promoImage\":\"https://res.cloudinary.com/dsaiqe6is/image/upload/v1555939074/Bank_Balance_Enquiry_c5wbrx.png\",\"promoUrl\":\"https://goo.gl/pGZQck\"},{\"promoName\":\"SmartDeals Lite - All in One Online Shopping App\",\"promoImage\":\"https://res.cloudinary.com/netq-recipes/image/upload/v1541490534/SmartDeals_Lite_a9ajj8.png\",\"promoUrl\":\"https://play.google.com/store/apps/details?id=com.tradetu.compare.online.shopping.dubai\"},{\"promoName\":\"RTO Vehicle Owner Information\",\"promoImage\":\"https://res.cloudinary.com/netq-recipes/image/upload/v1541490534/RTO_Vehicle_Owner_Information_q1gbto.png\",\"promoUrl\":\"https://play.google.com/store/apps/details?id=com.appsworld.trendingapps.vehicleownerdetails\"},{\"promoName\":\"All Village Maps India - ग्राम नक्शा\",\"promoImage\":\"https://res.cloudinary.com/netq-recipes/image/upload/v1541490532/All_Village_Maps_India_o8spvg.png\",\"promoUrl\":\"https://play.google.com/store/apps/details?id=com.tradetu.trendingapps.myvillage.villagemap\"},{\"promoName\":\"Learn & Improve English, Vocabulary, Dictionary\",\"promoImage\":\"https://res.cloudinary.com/netq-recipes/image/upload/v1541490528/Learn_English_zwondz.png\",\"promoUrl\":\"https://play.google.com/store/apps/details?id=com.tradetu.english.hindi.translate.language.word.dictionary\"},{\"promoName\":\"Offline Dictionary English Hindi - Learn English\",\"promoImage\":\"https://res.cloudinary.com/netq-recipes/image/upload/v1541490532/Offline_Dictionary_wz1i2n.png\",\"promoUrl\":\"https://play.google.com/store/apps/details?id=com.appsworld.trendingapps.offlinedictionary.english.hindi\"}]}";
    public static String sell_car_url = "https://inr.deals/2x0gK";
    public static boolean server_under_maintenance = false;
    public static boolean show_dealer_offers_button = true;
    public static boolean show_play_game_button = true;
    public static boolean show_rating_dialog = true;
    public static boolean show_search_challan_button = true;
    public static boolean show_sell_car_button = true;
    public static String site_url = "https://www.tradetu.com/rto/api/v1.0/";
    public static String update_bad_versions = "{\"versions\": [1,2,3,4,5,6]}";
    public static String update_change_log = "** Small bug fixes";
    public static boolean update_has_change_log = true;
    public static String update_min_version = "6";
    public static String update_new_version = "7";
}
